### ISSUE TITLE
Orientacja w P2

### ISSUE THREAD

**Issue by JuliaZur** [kjarosh/agh-graphs-project#8]
Jakby można zrobić tak żeby ta orientacja działała w metodzie _apply_, bo do testów produkcji 8 potrzebuję innej niż wychodzi.

**Comment by kjarosh** [comment]
@mickel8 jak status P2?

**Comment by mickel8** [comment]
@JuliaZur jak będzie ok. 16:30 to będzie okej?

**Comment by JuliaZur** [comment]
Tak pewnie, dzięki.
